<a href="https://colab.research.google.com/github/Nimira43/Deep-Learning-Pytorch/blob/main/funds_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix Multiplication

Two ways:

* Element wise multiplication
* Matrix multiplication - dot product

In [1]:
import torch

In [3]:
#Element wise

set1 = torch.tensor([1, 2, 3])
set1

tensor([1, 2, 3])

In [4]:
set2 = torch.tensor([3, 4, 8])
set2

tensor([3, 4, 8])

In [5]:
print(set1, " * ", set2)
print(f"Equal: {set1 * set2}")

tensor([1, 2, 3])  *  tensor([3, 4, 8])
Equal: tensor([ 3,  8, 24])


In [6]:
# Matrix multiplication

torch.matmul(set1, set2)

tensor(35)

Visualised

1 * 3 + 2 * 4 + 3 * 8

3 + 8 + 24

= 35


# Example 2

In [7]:
print(set1, " * ", set1) # element wise
print(f"Equal: {set1 * set1}")

tensor([1, 2, 3])  *  tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [8]:
torch.matmul(set1, set1) # matrix multiplication - matmul

tensor(14)

In [9]:
%%time
value = 0
for i in range(len(set1)):
  value += set1[i] * set1[i]
value #element wise

CPU times: user 0 ns, sys: 864 µs, total: 864 µs
Wall time: 5.13 ms


tensor(14)

In [10]:
%%time
torch.matmul(set1, set1) #matmul

CPU times: user 75 µs, sys: 0 ns, total: 75 µs
Wall time: 78.4 µs


tensor(14)

Dimensions

Inner dimension must match

(3, 2) @ (2, 3) ok

(2, 3) @ (3, 2) ok

(3, 2) @ (3, 2) error


In [13]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: ignored

In [14]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.3206, 0.2857, 0.6435],
        [0.6178, 0.4648, 1.0947],
        [0.6030, 0.2815, 0.7765]])