<a href="https://colab.research.google.com/github/Nimira43/Deep-Learning-Pytorch/blob/main/fund_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi


Sat Sep  9 21:33:05 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###Tensors - Scalar

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

Vector

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

Matrix

In [9]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

Tensor

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]]])
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
TENSOR = torch.tensor([[[[[23, 45, 53, 94, 23],
                          [93, 20, 21, 73, 36],
                          [63, 88, 31, 67, 75],
                          [73, 64, 99, 22, 61],
                          [38, 11, 86, 77, 38]]]]])
TENSOR.ndim

5

In [19]:
TENSOR.shape

torch.Size([1, 1, 1, 5, 5])

In [20]:
TENSOR[0]

tensor([[[[23, 45, 53, 94, 23],
          [93, 20, 21, 73, 36],
          [63, 88, 31, 67, 75],
          [73, 64, 99, 22, 61],
          [38, 11, 86, 77, 38]]]])

RANDOM TENSORS

In [21]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0232, 0.6775, 0.3371, 0.0617],
        [0.4299, 0.2899, 0.4220, 0.0208],
        [0.5067, 0.5894, 0.7041, 0.4703]])

In [22]:
random_tensor.ndim

2

In [29]:
random_tensor = torch.rand(1, 10, 10)
random_tensor

tensor([[[0.7730, 0.5911, 0.3071, 0.0330, 0.8072, 0.2942, 0.9285, 0.0605,
          0.1369, 0.4917],
         [0.8668, 0.8911, 0.7536, 0.1474, 0.4268, 0.8541, 0.1732, 0.5514,
          0.3756, 0.4900],
         [0.0808, 0.6230, 0.2562, 0.9600, 0.0274, 0.6985, 0.5445, 0.4171,
          0.0810, 0.0865],
         [0.3372, 0.1378, 0.3765, 0.6499, 0.0350, 0.1809, 0.1539, 0.3707,
          0.2955, 0.3298],
         [0.2741, 0.0223, 0.7408, 0.4288, 0.2991, 0.3147, 0.2089, 0.0158,
          0.3385, 0.3860],
         [0.0926, 0.5649, 0.9927, 0.3122, 0.5458, 0.1229, 0.9371, 0.5096,
          0.8494, 0.0754],
         [0.0633, 0.6501, 0.7619, 0.2212, 0.4907, 0.2346, 0.7137, 0.4174,
          0.6714, 0.9110],
         [0.9931, 0.2848, 0.2669, 0.9497, 0.3099, 0.7569, 0.2771, 0.9661,
          0.6126, 0.8739],
         [0.7791, 0.6742, 0.1788, 0.4536, 0.0772, 0.8504, 0.8261, 0.0665,
          0.7416, 0.7966],
         [0.4362, 0.5610, 0.5886, 0.6933, 0.5712, 0.2647, 0.7368, 0.2266,
          0.6289,

In [30]:
random_tensor.ndim

3

In [31]:
random_tensor.shape

torch.Size([1, 10, 10])

In [32]:
random_tensor = torch.rand(10, 10)
random_tensor

tensor([[0.2711, 0.3221, 0.5335, 0.6506, 0.5412, 0.5976, 0.1566, 0.3219, 0.2291,
         0.2765],
        [0.5922, 0.3208, 0.0866, 0.5016, 0.7539, 0.6448, 0.5286, 0.1710, 0.9491,
         0.2977],
        [0.1178, 0.0790, 0.8648, 0.0782, 0.2534, 0.5592, 0.2845, 0.6964, 0.2024,
         0.0928],
        [0.5816, 0.9484, 0.5876, 0.8569, 0.8673, 0.5533, 0.0728, 0.4418, 0.3791,
         0.1818],
        [0.2015, 0.6191, 0.3074, 0.8842, 0.0584, 0.5035, 0.5428, 0.9203, 0.9006,
         0.5828],
        [0.2070, 0.3731, 0.2106, 0.1068, 0.7819, 0.7708, 0.3746, 0.3400, 0.2292,
         0.1696],
        [0.6070, 0.1424, 0.0376, 0.3526, 0.6981, 0.6004, 0.1594, 0.9672, 0.1731,
         0.1134],
        [0.8784, 0.2907, 0.5013, 0.8753, 0.5723, 0.9724, 0.2924, 0.7274, 0.7773,
         0.5392],
        [0.9898, 0.5372, 0.4483, 0.5575, 0.9046, 0.6284, 0.3848, 0.4244, 0.9604,
         0.6392],
        [0.7546, 0.7822, 0.3319, 0.9257, 0.7727, 0.5470, 0.2461, 0.7804, 0.5383,
         0.4602]])

In [33]:
random_tensor.ndim

2

In [34]:
random_tensor.shape

torch.Size([10, 10])

Create a random tensor with similar shape to an image tensor

In [35]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
# where numbers are height, width, colour channels (RGB)
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [36]:
random_tensor2 = torch.rand(4, 12, 6)
random_tensor2

tensor([[[0.4544, 0.4873, 0.4942, 0.7412, 0.7082, 0.4218],
         [0.5749, 0.9154, 0.8113, 0.7286, 0.4418, 0.8912],
         [0.2525, 0.4259, 0.5633, 0.7518, 0.2293, 0.0067],
         [0.8119, 0.2113, 0.8996, 0.8409, 0.3213, 0.4971],
         [0.8278, 0.3382, 0.7322, 0.1800, 0.5430, 0.1861],
         [0.1504, 0.6489, 0.3016, 0.1456, 0.1991, 0.1527],
         [0.8655, 0.3433, 0.1682, 0.3117, 0.8194, 0.1977],
         [0.1134, 0.1266, 0.3811, 0.3485, 0.2716, 0.1845],
         [0.6760, 0.1394, 0.7402, 0.2631, 0.2327, 0.4483],
         [0.0763, 0.3075, 0.6480, 0.2865, 0.8929, 0.6293],
         [0.9216, 0.8465, 0.2898, 0.0016, 0.5643, 0.0069],
         [0.4949, 0.0822, 0.5312, 0.6265, 0.0817, 0.0367]],

        [[0.0158, 0.4512, 0.5864, 0.0290, 0.0950, 0.2840],
         [0.7428, 0.1438, 0.0455, 0.2756, 0.8852, 0.6492],
         [0.2393, 0.4425, 0.2055, 0.8559, 0.2229, 0.2408],
         [0.7440, 0.5292, 0.0739, 0.5493, 0.1290, 0.1625],
         [0.2131, 0.6416, 0.2810, 0.7893, 0.5396, 0.38

In [37]:
random_tensor2.ndim, random_tensor2.shape

(3, torch.Size([4, 12, 6]))

Zeros and ones

In [38]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype

torch.float32

Range of tensors and tensor-like

In [41]:
torch.range(0, 10)

<ipython-input-41-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
one_to_ten = torch.arange(start=200, end=2000, step=250)
one_to_ten

tensor([ 200,  450,  700,  950, 1200, 1450, 1700, 1950])

In [44]:
one_to_ten2 = torch.arange(start=1, end=11, step=1)
one_to_ten2

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
ten_zeros = torch.zeros_like(input=one_to_ten2)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [49]:
float_32_tensor = torch.tensor([3.0, 5.0, 8.0],
                               dtype=None)
float_32_tensor

tensor([3., 5., 8.])

In [51]:
torch.float32

torch.float32

In [54]:
float_32_tensor2 = torch.tensor([3.0, 5.0, 8.0],
                               dtype=None, # what datatype - 32 bit floating point and 16 bit floating point are most common
                               device=None, # what device is your tensor on - ie CPU, GPU or TPU
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor2

tensor([3., 5., 8.])

In computer science, the precision of a numerical quantity is a measure of the detail in which the quantity is expressed. This is usually measured in bits, but sometimes in decimal digits. It is related to precision in mathematics, which describes the number of digits that are used to express a value.

Some of the standardized precision formats are

*   Half-precision floating-point format = float16
*   Single-precision floating-point format = float32
*   Double-precision floating-point format = float64
*   Quadruple-precision floating-point format
*   Octuple-precision floating-point format

Of these, octuple-precision format is rarely used. The single- and double-precision formats are most widely used and supported on nearly all platforms. The use of half-precision format has been increasing especially in the field of machine learning since many machine learning algorithms are inherently error-tolerant.

Tensor datatypes is one of the 3 big errors that you'll run into with PyTorch and deep learning:
* Tensors not right datatype
* Tensors not right shape
* Tensor not on right device



In [58]:
float_32_tensor2.dtype

torch.float32

In [59]:
float_16_tensor = float_32_tensor2.type(torch.float16) # how to convert float tensor - in this case converting a 32 bit tensor into a 16 bit tensor
float_16_tensor

tensor([3., 5., 8.], dtype=torch.float16)

In [62]:
float_16_tensor * float_32_tensor2

tensor([ 9., 25., 64.])

In [65]:
int_32_tensor = torch.tensor([4, 5, 9], dtype=torch.int32)
int_32_tensor

tensor([4, 5, 9], dtype=torch.int32)

In [66]:
int_32_tensor * float_16_tensor

tensor([12., 25., 72.], dtype=torch.float16)

Getting information from tensors:

* Tensors not right datatype - tensor.dtype
* Tensors not right shape = tensor.shape
* Tensor not on right device = tensor.device



In [67]:
test = torch.rand([3, 5])
test

tensor([[0.8665, 0.6007, 0.4783, 0.2385, 0.7148],
        [0.9890, 0.9780, 0.6193, 0.2665, 0.4752],
        [0.2343, 0.4702, 0.9292, 0.4377, 0.9813]])

In [69]:
print(test)
print(f"Datatype of tensor: {test.dtype}")
print(f"Shape of tensor: {test.shape}")
print(f"Device type of tensor: {test.device}")

tensor([[0.8665, 0.6007, 0.4783, 0.2385, 0.7148],
        [0.9890, 0.9780, 0.6193, 0.2665, 0.4752],
        [0.2343, 0.4702, 0.9292, 0.4377, 0.9813]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 5])
Device type of tensor: cpu


Functions and Attributes

test.size() - this is a function

test.shape - this is an attribute

Manipulating Tensors (Tensor Operations)

such as addition, subtraction, multiplication, division and matrix multiplication

In [76]:
tensor1 = torch.tensor([2, 5, 8])
tensor1 + 10

tensor([12, 15, 18])

In [77]:
tensor1

tensor([2, 5, 8])

In [78]:
tensor1 = tensor1 * 3
tensor1

tensor([ 6, 15, 24])

In [79]:
tensor2 = tensor1 - 2
tensor2

tensor([ 4, 13, 22])

In [81]:
torch.mul(tensor2, 3)


tensor([12, 39, 66])

In [82]:
tensor3 = torch.add(tensor1, tensor2)
tensor3

tensor([10, 28, 46])

In [83]:
tensor4 = torch.mul(tensor2, tensor3)
tensor4

tensor([  40,  364, 1012])

In [84]:
tensor4.dtype

torch.int64